### ISSUE TITLE
Translations don't work

### ISSUE THREAD

**Issue by smartcorestudio** [faiyaz26/Select-All-Context-Menu-CKEditor#1]
Hi! I've created custom CKeditor build with your plugin. All other plugins are translated correctly, but in the context menu I see "Select All" label (in English). Maybe there's something wrong with the structure of language files? Maybe we need to replace `"toolbar"` to `"label"`?

**Comment by faiyaz26** [comment]
Thank you for reporting this bug, I have fixed it and uploaded to the CKeditor's plugin repo. Can you please check and let me if it works ?

**Comment by smartcorestudio** [comment]
Thanks a lot! It works!
